---
abstract: 'A simple Mustach Renderer'
author:
  - 'Cliff Stanford <cpan@may.be>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.9, CPAN::Meta::Converter version 2.131560'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mustache-Simple
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: 0
  perl: 0
version: v1.0.0
