---
abstract: 'A simple Mustach Renderer'
author:
  - 'Cliff Stanford <cpan@may.be>'
build_requires:
  Test::More: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.96, CPAN::Meta::Converter version 2.140640'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Mustache-Simple
no_index:
  directory:
    - t
    - inc
requires:
  File::Spec: '0'
  YAML::XS: '0'
  experimental: '0.008'
  perl: '5.010000'
version: v1.2.3
